export const items = [
  // Types would be "weapon", "armor", or "potion"
  {
    name: "dagger",
    type: "weapon",
    value: 4,
    cost: 5,
    description: "",
    imgSource: "",
  },
  {
    name: "sword",
    type: "weapon",
    value: 8,
    cost: 10,
    description: "",
    imgSource: "",
  },
  {
    name: "axe",
    type: "weapon",
    value: 12,
    cost: 15,
    description: "",
    imgSource: "",
  },
  {
    name: "health potion",
    type: "potion",
    value: 10,
    cost: 5,
    description: "",
    imgSource: "",
  },
  {
    name: "leather armor",
    type: "armor",
    value: 5,
    cost: 10,
    description: "",
    imgSource: "",
  },
  {
    name: "chainmail armor",
    type: "armor",
    value: 10,
    cost: 20,
    description: "",
    imgSource: "",
  },
  {
    name: "plate armor",
    type: "armor",
    value: 15,
    cost: 30,
    description: "",
    imgSource: "",
  },
  {
    name: "shield",
    type: "armor",
    value: 2,
    cost: 18,
    description: "",
    imgSource: "",
  },
  {
    name: "spear",
    type: "weapon",
    value: 6,
    cost: 8,
    description: "",
    imgSource: "",
  },
];
